version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vue-i18n
    versions:
    - 8.22.4
    - 8.23.0
    - 8.24.0
    - 8.24.1
    - 8.24.2
    - 8.24.3
  - dependency-name: codemirror
    versions:
    - 5.59.2
    - 5.59.3
    - 5.59.4
    - 5.60.0
  - dependency-name: highlight.js
    versions:
    - 10.5.0
    - 10.6.0
    - 10.7.1
  - dependency-name: clipboard
    versions:
    - 2.0.6
    - 2.0.7
  - dependency-name: lint-staged
    versions:
    - 10.5.3
